language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP=files_paperhive
  matrix:
    - DB=sqlite;
    - DB=mysql;

branches:
  only:
    - master

before_install:
  - cd ../
  - git clone https://github.com/owncloud/core.git --recursive --depth 1 -b $CORE_BRANCH
  - mv $APP core/apps/
  - cd core
  - composer install

before_script:
  # Setup MySQL if applicable
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
  - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - php occ app:enable $APP
  - cd apps/$APP

script:
  # Run phpunit tests
  - cd tests
  - ../../../lib/composer/bin/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
