language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP=files_paperhive
  matrix:
    - DB=sqlite;
    - DB=mysql;

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP

before_script:
  - cd apps/$APP

script:
  # Run phpunit tests
  - cd tests
  - ../../../lib/composer/bin/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
