language: php
sudo: false
php:
  - 5.6
  - 7
  - 7.1

env:
  global:
    - CORE_BRANCH=master
    - APP=files_paperhive
  matrix:
    - DB=sqlite;

matrix:
  include:
    - php: 5.4
      env: DB=sqlite CORE_BRANCH=stable9
    - php: 5.4
      env: DB=sqlite CORE_BRANCH=stable9.1
  fast_finish: true

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP

before_script:
  - cd apps/$APP

script:
  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  fast_finish: true
